### PR TITLE
Custom Capes Support

### PR DESCRIPTION
**Pull request by noahmaue**
If you can make it run "LoadCustomCapes()" when the capes page is opened, then any custom capes from the "customCapes" object will be shown! There's also some form of support for viewing them on user's profiles, but it appears I cannot make the canvas' work.

### CODE REVIEW

**Comment by emmsixx** [comment]
Sounds good! I'll take a look into it and implement it into the main build. As for getting capes to work on profiles, you need to make your own skinview3d instance to then be able to add stuff to. This is currently in the development build which has not yet been uploaded anywhere (even to dev branch).

**Comment by noahmaue** [comment]
Thanks for the update! But by profile support, I meant this.
image
Currently the window appears, but the capes refuse to show up.

EDIT: You should run "LoadUserCustomCapes(uuid)" when the profile is loaded to make it appear appropriately.
EDIT EDIT: I fixed it and sent the new script in the Discord.

**Comment by emmsixx** [comment]
Update: I've partially added it in, but at the moment things are buggy and only username: xinabox has it at the moment. In the meantime, I will keep this request open until I figure something out.

**Comment by noahmaue** [comment]
Looks good so far, but may I ask why you opted to store it in Base64 inside the JS file itself? You can set a canvas image to both local images and URLs (I personally used imgur when I was testing my code)

**Comment by emmsixx** [comment]
Storing it in the JS file was a temporary, "quick" way to do it. At the moment I am working on rewriting it to use image URL's hosted on m6.wtf

**Pull request closed without merging**
