### PR TITLE
Improve the installation section

### PR DESCRIPTION
**Pull request by amsam0**
Very small improvement that adds a direct link to download ZIP.

### CODE REVIEW

**Review by noahmaue — APPROVED** [review]
Thank you for contributing!

**Comment by amsam0** [comment]
🤔

Why did it get reverted?

**Comment by noahmaue** [comment]
idk man M6 is like that sometimes

**Comment by emmsixx** [comment]
I tried to revert it because you're on the contributor list even though you only added one line to the readme. However completely wiping it from the commit history did not seem to remove you from contributor list. Sorry for the misunderstanding.

**Pull request merged**
